name: Test build

on: 
  push:
    paths:
    - 'addons/sourcemod/scripting/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SM_VERSION: ["1.11", "1.12"]

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Set environment variables
        run: |
          SOURCEMOD_PATH=$GITHUB_WORKSPACE
          echo "SOURCEMOD_PATH=$SOURCEMOD_PATH" >> $GITHUB_ENV
          echo "SCRIPTING_PATH=$SOURCEMOD_PATH/scripting" >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@v1.2.4
        with:
          version: ${{ matrix.SM_VERSION }}

      - name: Compiling plugins
        run: |
          for file in *.sp
          do
            echo -e "\nCompiling $file..."
            spcomp -E -w234 -O2 -v2 -i $SCRIPTING_PATH/include $file
          done
        working-directory: ${{ env.SCRIPTING_PATH }}/
